############# English navigation ##############

# main menu

[[main]]
name = "accueil"
url = ""
weight = 1

[[main]]
name = "à propos"
url = "about/"
weight = 2


[[main]]
name = "contact"
url = "contact/"
weight = 4

[[main]]
name = "blog"
url = "blog/"
weight = 3

